name: tricount
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  http: ^1.1.0
  image_picker: ^1.0.4
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  supabase_flutter: ^1.10.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
